services:
  control:
    image: alpine:3.17
    container_name: control
    hostname: control
    command: "/config/config_creator.sh"
    volumes:
      - telegraf_etc:/telegraf
      - swag:/swag
      - ./config:/config:ro

  swag:
    image: mc-swag:latest
    container_name: swag
    hostname: swag
    depends_on:
      - control
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - URL=yourdomain.url
      - VALIDATION=http
      - SUBDOMAINS=telegraf
      - ONLY_SUBDOMAINS=true
      #- EMAIL=
    volumes:
      - swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  sshd:
    image: mc-sshd:latest
    container_name: sshd
    hostname: sshd
    depends_on:
      - control
    environment:
      # Username and sshd configuration is a part of build script
      - PASS=Test1234!
      #- PUBKEY=      
    volumes:
      - telegraf_var:/opt/telegraf/var
    ports:
      - 2222:22
    restart: unless-stopped

  telegraf-sdwan-twamp:
    image: mc-telegraf:latest
    container_name: telegraf-sdwan-twamp
    hostname: telegraf-sdwan-twamp
    depends_on:
      - control
    environment:
      - CONFIG=sdwan-twamp.conf
    volumes:
      - telegraf_var:/opt/telegraf/var
      - telegraf_etc:/opt/telegraf/etc:ro
    restart: unless-stopped

  telegraf-sdwan-mtr:
    image: mc-telegraf:latest
    container_name: telegraf-sdwan-mtr
    hostname: telegraf-sdwan-mtr
    depends_on:
      - control
    environment:
      - CONFIG=sdwan-mtr.conf
    volumes:
      - telegraf_var:/opt/telegraf/var
      - telegraf_etc:/opt/telegraf/etc:ro
    restart: unless-stopped

  telegraf-tier1-twamp:
    image: mc-telegraf:latest
    container_name: telegraf-tier1-twamp
    hostname: telegraf-tier1-twamp
    depends_on:
      - control
    environment:
      - CONFIG=tier1-twamp.conf
    volumes:
      - telegraf_var:/opt/telegraf/var
      - telegraf_etc:/opt/telegraf/etc:ro
    restart: unless-stopped

  telegraf-tier1-mtr:
    image: mc-telegraf:latest
    container_name: telegraf-tier1-mtr
    hostname: telegraf-tier1-mtr
    depends_on:
      - control
    environment:
      - CONFIG=tier1-mtr.conf
    volumes:
      - telegraf_var:/opt/telegraf/var
      - telegraf_etc:/opt/telegraf/etc:ro
    restart: unless-stopped

  telegraf-atlas:
    image: mc-telegraf:latest
    container_name: telegraf-atlas
    hostname: telegraf-atlas
    depends_on:
      - control
    environment:
      - CONFIG=atlas.conf
    volumes:
      - telegraf_var:/opt/telegraf/var
      - telegraf_etc:/opt/telegraf/etc:ro
    restart: unless-stopped

volumes:
  swag:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ..../swag-config
  telegraf_var:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .../telegraf-var
  telegraf_etc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .../telegraf-config
